### ISSUE TITLE
Got error when install ember-cli-simple-auth on ember-cli 0.2.4

### ISSUE THREAD

**Issue by avkprog** [simplabs/ember-cli-simple-auth#31]
Upgrade ember-cli to 0.2.4. When i run

```
ember install ember-cli-simple-auth
```

Here is output

```
ember install ember-cli-simple-auth
version: 0.2.4
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /home/ak/www/jsprojects/test-auth/node_modules/ember-cli/lib/models/project.js:475:53
    at baseFindIndex (/home/ak/www/jsprojects/test-auth/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /home/ak/www/jsprojects/test-auth/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/home/ak/www/jsprojects/test-auth/node_modules/ember-cli/lib/models/project.js:474:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/home/ak/www/jsprojects/test-auth/node_modules/ember-cli/lib/tasks/addon-install.js:63:30)
    at Class.module.exports.Task.extend.installBlueprint (/home/ak/www/jsprojects/test-auth/node_modules/ember-cli/lib/tasks/addon-install.js:52:30)
    at Class.<anonymous> (/home/ak/www/jsprojects/test-auth/node_modules/ember-cli/lib/tasks/addon-install.js:42:19)
    at lib$rsvp$$internal$$tryCatch (/home/ak/www/jsprojects/test-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/ak/www/jsprojects/test-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/ak/www/jsprojects/test-auth/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

**Comment by jchn** [comment]
Got the same error and not only with this addon, but with others as well. Had to switch back to ember-cli 0.2.3.

**Comment by marcoow** [comment]
This is a bug in Ember CLI - see ember-cli/ember-cli#4085. You need to update the `ember-cli-dependency-checker` to 1.0.1 until the Ember CLI team will release a fix for this later today.
